#one mean parametric test
print("enter the data",quotes=FALSE)
data<-scan()
print("enter the mu value",quotes=FALSE)
u<-scan()
print("enter the level of significance",quotes=FALSE)
al<-scan()
s<-sd(data)
print("the given data:",quotes=FALSE)
print(data)
print("the mu value of given data:",quotes=FALSE)
print(u)
print("level of significance of given data",quotes=FALSE)
print(al)
print("the standard deviation of given data:",quotes=FALSE)
print(s)
t<-t.test(data,mu=u)
print("the calculated t value:",quotes=FALSE)
print(t)
#t<-t.test(data,mu=mu,alternative="less")
#print(t)
#t<-t.test(data,mu=mu,alternative="greater")
#print(t)
print("Table value for two-tailed test:")
tablevalue<-qt(1-al/2, df=n-1)
print(round(tablevalue,digits=3))
print("Table value for one-tailed test:")
tablevalue<-qt(1-al, df=n-1)
print(round(tablevalue,digits=3))
