print("enter x observations")
x<-scan()
print("enter y observations")
y<-scan()
print("enter los")
alpha<-scan()
di<-(x-y)
n<-length(di)
dbar<-mean(di)
std<-sd(di)
values<-c(dbar,std)
print("values of dbar and sd of difference")
print(round(values,digits=4))
t<-round((dbar-0)/std/sqrt(n),digits=3)
print(paste("calculated t value is:",t))
print("using the built in function")
t<-t.test(x,y,paired=TRUE)
print(t)
print("table value for one tailed test")
t_v<-qt(1-alpha,df=n-1)
print(round(t_v,digits=3))
