#two mean parametric test
print("enter the two data",quoes=FALSE)
x<-scan()
y<-scan()
print("enter the level of significance",quotes=FALSE)
al<-scan()
nx<-length(x)
ny<-length(y)
sd=sqrt((((nx-1)*sd(x)^2)+(ny-1)*sd(y)^2)/(nx+ny-2))
t=(mean(x)-mean(y))/(sd*sqrt((1/nx)+(1/ny)))
print("mean of x:")
print(mean(x))
print("mean of y:")
print(mean(y))
print("Combined SD")
print(sd)
print("Calculated value of t:")
print(round(t,digits=4))
t<-t.test(x,y)
print(t)
print("Table value for two-tailed test:")
tablevalue<-qt(1-al/2, df=n1+n2-2)
print(round(tablevalue,digits=3))
print("Table value for one-tailed test:")
tablevalue<-qt(1-al, df=n1+n2-2)
print(round(tablevalue,digits=3))
